# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import beacon_pb2 as beacon__pb2


class BeaconStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handle = channel.unary_unary(
                '/beacon.Beacon/Handle',
                request_serializer=beacon__pb2.BeaconIncoming.SerializeToString,
                response_deserializer=beacon__pb2.BeaconOutgoing.FromString,
                )


class BeaconServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Handle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeaconServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handle': grpc.unary_unary_rpc_method_handler(
                    servicer.Handle,
                    request_deserializer=beacon__pb2.BeaconIncoming.FromString,
                    response_serializer=beacon__pb2.BeaconOutgoing.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beacon.Beacon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Beacon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Handle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beacon.Beacon/Handle',
            beacon__pb2.BeaconIncoming.SerializeToString,
            beacon__pb2.BeaconOutgoing.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
